//
//  Copy.swift
//  
//
//  Created by Noah Little on 6/5/2023.
//

import Foundation
import GSCore

enum Copy {
    static let appearance = "APPEARANCE".localize(bundle: .dodo)
    static let timeAndMediaStyle = "TIME_MEDIA_STYLE".localize(bundle: .dodo)
    static let modular = "MODULAR".localize(bundle: .dodo)
    static let classic = "CLASSIC".localize(bundle: .dodo)
    static let showDivider = "SHOW_DIVIDER".localize(bundle: .dodo)
    static let showDividerDesc = "SHOW_DIVIDER_DESC".localize(bundle: .dodo)
    static let showSuggestions = "SHOW_SUGGESTIONS".localize(bundle: .dodo)
    static let showSuggestionsDesc = "SHOW_SUGGESTIONS_DESC".localize(bundle: .dodo)
    static let marqueeLabels = "MARQUEE_LABELS".localize(bundle: .dodo)
    static let marqueeLabelsDesc = "MARQUEE_LABELS_DESC".localize(bundle: .dodo)
    static let timeAndMediaPlayer = "TIME_AND_MEDIA_PLAYER".localize(bundle: .dodo)
    static let chooseOverallAppearance = "CHOOSE_OVERALL_APPEARANCE".localize(bundle: .dodo)
    static let time = "TIME".localize(bundle: .dodo)
    static let mediaPlayer = "MEDIA_PLAYER".localize(bundle: .dodo)
    static let bothTimeAndMediaPlayer = "BOTH_TIME_MEDIA_PLAYER".localize(bundle: .dodo)
    static let onlyShowTime = "ONLY_SHOW_TIME".localize(bundle: .dodo)
    static let onlyShowMediaPlayer = "ONLY_SHOW_MEDIA_PLAYER".localize(bundle: .dodo)
    static let showTimeAndMediaPlayer = "SHOW_TIME_MEDIA_PLAYER".localize(bundle: .dodo)
    static let timeColor = "TIME_COLOR".localize(bundle: .dodo)
    static let dateColor = "DATE_COLOR".localize(bundle: .dodo)
    static let dividerColor = "DIVIDER_COLOR".localize(bundle: .dodo)
    static let colors = "COLORS".localize(bundle: .dodo)
    static let playerButtonTheme = "PLAYER_BUTTON_THEME".localize(bundle: .dodo)
    static let theming = "THEMING".localize(bundle: .dodo)
    static let themingDesc = "THEMING_DESC".localize(bundle: .dodo)
    static let font = "FONT".localize(bundle: .dodo)
    static let timeFontSize = "TIME_FONT_SIZE".localize(bundle: .dodo)
    static let dateFontSize = "DATE_FONT_SIZE".localize(bundle: .dodo)
    static let weatherFontSize = "WEATHER_FONT_SIZE".localize(bundle: .dodo)
    static let fonts = "FONTS".localize(bundle: .dodo)
    static let fontsFooter = "FONTS_FOOTER".localize(bundle: .dodo)
    static let `default` = "DEFAULT".localize(bundle: .dodo)
    static let custom = "CUSTOM".localize(bundle: .dodo)
    static let monospaced = "MONOSPACED".localize(bundle: .dodo)
    static let rounded = "ROUNDED".localize(bundle: .dodo)
    static let serif = "SERIF".localize(bundle: .dodo)
    static let behaviour = "BEHAVIOUR".localize(bundle: .dodo)
    static let timeFormat = "TIME_FORMAT".localize(bundle: .dodo)
    static let twentyFourHourMode = "TWENTY_FOUR_HOUR_MODE".localize(bundle: .dodo)
    static let timeFormatting = "TIME_FORMATTING".localize(bundle: .dodo)
    static let dateFormat = "DATE_FORMAT".localize(bundle: .dodo)
    static let dateFormatting = "DATE_FORMATTING".localize(bundle: .dodo)
    static let favouriteApps = "FAVOURITE_APPS".localize(bundle: .dodo)
    static let favouriteAppsDesc = "FAVOURITE_APPS_DESC".localize(bundle: .dodo)
    static let statusIndicators = "STATUS_INDICATORS".localize(bundle: .dodo)
    static let statusIndicatorsDesc = "STATUS_INDICATORS_DESC".localize(bundle: .dodo)
    static let weather = "WEATHER".localize(bundle: .dodo)
    static let weatherDesc = "WEATHER_DESC".localize(bundle: .dodo)
    static let notificationVerticalOffset = "NOTIFICATION_Y_OFFSET".localize(bundle: .dodo)
    static let dimensions = "DIMENSIONS".localize(bundle: .dodo)
    static let chargingFlash = "CHARGING_FLASH".localize(bundle: .dodo)
    static let chargingFlashDesc = "CHARGING_FLASH_DESC".localize(bundle: .dodo)
    static let misc = "MISC".localize(bundle: .dodo)
    static let preview = "PREVIEW".localize(bundle: .dodo)
    static let showSeconds = "SHOW_SECONDS".localize(bundle: .dodo)
    static let enabled = "ENABLED".localize(bundle: .dodo)
    static let favouriteAppsOnLS = "FAVOURITE_APPS_ON_LS".localize(bundle: .dodo)
    static let apps = "APPS".localize(bundle: .dodo)
    static let selectYourApps = "SELECT_YOUR_APPS".localize(bundle: .dodo)
    static let showFade = "SHOW_FADE".localize(bundle: .dodo)
    static let showFadeDesc = "SHOW_FADE_DESC".localize(bundle: .dodo)
    static let gridType = "GRID_TYPE".localize(bundle: .dodo)
    static let flexibleItemSize = "FLEXIBLE_ITEM_SIZE".localize(bundle: .dodo)
    static let fixedItemSize = "FIXED_ITEM_SIZE".localize(bundle: .dodo)
    static let flexibleColumnAmount = "FLEXIBLE_COLUMN_AMOUNT".localize(bundle: .dodo)
    static let fixedColumnAmount = "FIXED_COLUMN_AMOUNT".localize(bundle: .dodo)
    static let layout = "LAYOUT".localize(bundle: .dodo)
    static let layoutFooter = "LAYOUT_FOOTER".localize(bundle: .dodo)
    static let flexible = "FLEXIBLE".localize(bundle: .dodo)
    static let fixed = "FIXED".localize(bundle: .dodo)
    static let adaptive = "ADAPTIVE".localize(bundle: .dodo)
    static let displayIndicators = "DISPLAY_INDICATORS".localize(bundle: .dodo)
    static let showWhenDisabled = "SHOW_WHEN_DISABLED".localize(bundle: .dodo)
    static let showWhenDisabledDesc = "SHOW_WHEN_DISABLED_DESC".localize(bundle: .dodo)
    static let indicatorSize = "INDICATOR_SIZE".localize(bundle: .dodo)
    static let size = "SIZE".localize(bundle: .dodo)
    static let color = "COLOR".localize(bundle: .dodo)
    static let lock = "LOCK".localize(bundle: .dodo)
    static let charging = "CHARGING".localize(bundle: .dodo)
    static let alarm = "ALARM".localize(bundle: .dodo)
    static let dnd = "DND".localize(bundle: .dodo)
    static let flashlight = "FLASHLIGHT".localize(bundle: .dodo)
    static let vibration = "VIBRATION".localize(bundle: .dodo)
    static let muted = "MUTED".localize(bundle: .dodo)
    static let seconds = "SECONDS".localize(bundle: .dodo)
    static let unavailableRootless = "UNAVAILABLE_ROOTLESS".localize(bundle: .dodo)
    static let weatherFooter = "WEATHER_FOOTER".localize(bundle: .dodo)
    static let autoRefresh = "AUTO_REFRESH".localize(bundle: .dodo)
    static let options = "OPTIONS".localize(bundle: .dodo)
    static let showMediaBackdrop = "SHOW_MEDIA_BACKDROP".localize(bundle: .dodo)
    static let showMediaBackdropDesc = "SHOW_MEDIA_BACKDROP_DESC".localize(bundle: .dodo)

    static func indicator(_ string: String) -> String {
        .init(format: "INDICATOR".localize(bundle: .dodo), string)
    }
}
